export enum TransactionState {
  INITIATED = "INITIATED",
  NAIRA_DEBITED = "NAIRA_DEBITED",
  FX_CONVERTED = "FX_CONVERTED",
  USDC_SENT = "USDC_SENT",
  CEDIS_CREDITED = "CEDIS_CREDITED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED"
}
